---
title: ""
execute:
  echo: false
  warning: false
  message: false
format:
  html:
    theme: cosmo
---

```{r}
knitr::opts_chunk$set(echo = FALSE)

options(reactable.static = TRUE)
```

```{css ref.label="styles", echo=FALSE}
```

```{r ref.label="font_styles", echo=FALSE}
```

```{css ref.label="pkgdown_styles", echo=FALSE}
```

```{r}
source("scripts/acb_dre.R")

tbl <- reactable(
  df %>%
    mutate(dre = round(dre, 1)) %>%
    select(-equipo, -abb, -rival, -matches, -logo_cuadrado),
  columns = list(
    license_license_str15 = colDef(
      name = "",
      html = TRUE,
      cell = function(value, index) {
        htmltools::HTML(
          combine_word(
            license_license_str15 = value,
            rival = df$rival[index],
            logo_cuadrado = df$logo_cuadrado[index]
          )
        )
      }
    ),
    time_played = colDef(name = "Min",  align = "right", vAlign = "center"),
    ts_pct = colDef(name = "Ts%", align = "right", vAlign = "center"),
    usg_pct = colDef(name = "Usg%",  align = "right", vAlign = "center"),
    points = colDef(name = "Pts", vAlign = "center"),
    asis = colDef(name = "Ast",  vAlign = "center"),
    total_rebound = colDef(name = "Reb",  vAlign = "center"),
    turnovers = colDef(name = "Tot",  vAlign = "center"),
    steals = colDef(name = "Stl", vAlign = "center"),
    blocks = colDef(name = "Blk", vAlign = "center"),
    x2pm_a = colDef(name = "2pt", align = "right", vAlign = "center"),
    x3pm_a = colDef(name = "3pt", align = "right", vAlign = "center"),
    x1pm_a = colDef(name = "1pt", align = "right", vAlign = "center"),
    val = colDef(name = "Val", align = "center", vAlign = "center"),
    dre = colDef(name = "Dre", align = "center", vAlign = "center"),
    differential = colDef(name = "+/-",  vAlign = "center")
  ),
  pagination = TRUE,
  filterable = TRUE,
  highlight = TRUE,
  width = "100%",
  defaultPageSize = 25,
  theme = reactableTheme(
    header = list(
      borderBottom = "3px solid black",
      textAlign = "center" # centra los nombres del header
    ),
    style = list(
      fontFamily = "Oswald",
      fontSize = "9.5pt"
    )
  )
)

div(
  class = "content-wrapper",
  div(
    class = "standings",
    div(
      class = "title",
      h1("Los Mejores De La Jornada 7"),
      "Soccer Power Index (SPI) ratings and chances of advancing for every team"
    ),
    tbl,
    "Forecast from before 3rd group matches"
  )
)
```

```{r font_styles, eval=FALSE}
htmltools::tags$link(
  href = "https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&display=swap",
  rel  = "stylesheet"
)
```

```{css styles, eval=FALSE}

.standings {
  font-family: Oswald, sans-serif;
  font-style:700;
  
}
.title {
 
  margin-bottom: 1.125rem;
 font-family: Oswald, sans-serif;
  font-size: 0.95rem;
}

.title h1 {
line-height: 8px;
  font-size: 1.75rem;
  font-weight: 600;
}

.content-wrapper {
  max-width: 600px;   /* prueba 650–800 según te guste */
  margin: 0 auto;     /* centra el contenido */
}
```
