name: Prueba 5 y 3

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - name: Instalar dependencias de R
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            dplyr,
            readr,
            tidyr,
            stringr,
            janitor,
            purrr,
            lubridate,
            gt,
            gtExtras
            extra-packages: |
            andreweatherman/gtUtils      
      - name: Run R script
        run: Rscript scripts/dre_top5.R

      - name: Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add png/*.png
          git commit -m "Auto update" || true
          git push
